### PR TITLE
Config file and Tests

### PR DESCRIPTION
**Pull request by brettz9**
Builds on #8.

- Enhancement(binary): Support passing in `--config` file (used also in tests)
- Enhancement(binary): Support `timeout`
- Enhancement: Re-export `listify` and `streamtoString`
- Enhancement: If `tls` is set, default port to 995
- Enhancement: Add source maps
- Enhancement: Throw `no-socket` Error in `command` if no socket left
- Fix: Add `bad-server-response` error (handle obscure case where server doesn't follow spec or gives unknown response)
- Fix: Reject `command` early upon error
- Fix (CLI): For other commands, use `_connect` instead of `connect` to allow necessary authentication before practical use
- Fix (CLI): Allow boolean args at any posiiton
- Fix (CLI): Report bad alias (though ignore empty `--` arg)
- Fix (CLI) Avoid including reference to promise being uncaught in reported errors; catch any errors ourselves but log error to stderr
- Fix (CLI): Ensure `QUIT` in CLI usage after every other command
- Update: Avoid deprecated `new Buffer` in favor of `Buffer.from`
- Docs: Some nits
- Testing: Add Mocha + NYC testing

I would appreciate it if you could let me know whether you are still maintaining. I appreciate the good foundation you set up! Thank you!

### CODE REVIEW

**Comment by brettz9** [comment]
Now at 100% coverage

**Comment by brettz9** [comment]
If you're no longer maintaining, I might add another fork, but I'd appreciate being spared the extra work if you might have some time later to take a look.

**Comment by lianxh** [comment]
> If you're no longer maintaining, I might publish my fork, but I'd appreciate being spared the extra work if you might have some time later to take a look.

I feel sorry to reply your message so late and I may have no time to maintain this repository recently. Thanks for your work which will help more people and you can publish your fork if you want :)

**Comment by brettz9** [comment]
Thank you for the merges! 谢谢！🙏  

If you mean you may have no time in the future to maintain, would you prefer to share commit access or to transfer the repository to a Github organization we create to which we both have access? Then users could keep using the same npm package (and if you didn't want to deal with publishing, you could add me as a package owner also).

If you just mean you have been busy and may have more time now to review, I have a few additional smaller but breaking changes to offer or ask about.

Best wishes!

**Comment by lianxh** [comment]
> Thank you for the merges! 谢谢！🙏
> 
> If you mean you may have no time in the future to maintain, would you prefer to share commit access or to transfer the repository to a Github organization we create to which we both have access? Then users could keep using the same npm package (and if you didn't want to deal with publishing, you could add me as a package owner also).
> 
> If you just mean you have been busy and may have more time now to review, I have a few additional smaller but breaking changes to offer or ask about.
> 
> Best wishes!

I`d like to transfer the repository to a Github organization and add you as a package owner, but I don`t know how to do that 😅
I have invited you to accept a manage access for this repository, will it can allowed you to implement your suggestions?

**Comment by brettz9** [comment]
If you still want to transfer it, there is an option in Settings. But it is no problem for me to work on this repository.

Would you like me to only commit small fixes directly and submit PRs for review? Or are you too busy and just want me to manage it? If the latter, I'll still need to ask for your help with npm publishing (unless you run `npm owner add brettz9`). But I am very happy to have your reviews and final control if you have the time to review and publish.

**Comment by lianxh** [comment]
> If you still want to transfer it, there is an option in Settings. But it is no problem for me to work on this repository.
> 
> Would you like me to only commit small fixes directly and submit PRs for review? Or are you too busy and just want me to manage it? If the latter, I'll still need to ask for your help with npm publishing (unless you run `npm owner add brettz9`). But I am very happy to have your reviews and final control if you have the time to review and publish.

I hope you can manage this repository and I have created a organization and sent a invitation to you, meanwhile I add you as a owner in npm. Recently I may not have the time to review your commits, so you can manage and publish it by yourself. If there are some others that I can help for you, please let me know, thanks.

**Comment by brettz9** [comment]
Ok, great, thanks! I've bumped `engines` (as we needed it to be at least Node 6), added a CHANGES.md file, and published a new release. Hope to add another breaking changes release soon as well. Thanks again!

**Pull request merged**
